In [5]:
import numpy as np 
import pandas as pd

In [6]:
covidPath = "C:/Users/camil/OneDrive/Bureau/COVID19_03242020_ByCounty.xlsx"
covid = pd.read_excel(covidPath)

In [7]:
covid.head()

,OBJECTID_12_13,OBJECTID,DEPCODE,COUNTY,COUNTYNAME,DATESTAMP,ShapeSTAre,ShapeSTLen,OBJECTID_1,County_1,...,T_negative,T_pending,T_positive,FLandNonFLDeaths,EverMon,MonNow,Shape__Area,Shape__Length,Shape_Length,Shape_Area
0,1,1,21,41,GILCHRIST,2000-05-16T00:00:00.000Z,9.908353e+09,4.873000e+05,21,Gilchrist,...,7,0,0,0,0,0,9.204908e+08,148547.348006,148547.347588,9.204908e+08
1,2,2,54,107,PUTNAM,2000-05-16T00:00:00.000Z,2.305869e+10,7.629677e+05,54,Putnam,...,81,28,2,0,0,0,2.142439e+09,232574.925675,232574.926296,2.142439e+09
2,3,3,62,123,TAYLOR,2000-05-16T00:00:00.000Z,2.891747e+10,8.772527e+05,62,Taylor,...,12,0,0,0,0,0,2.685253e+09,267348.178950,267348.178429,2.685253e+09
3,4,4,46,91,OKALOOSA,2000-05-16T00:00:00.000Z,2.562159e+10,1.087058e+06,46,Okaloosa,...,62,15,14,0,58,16,2.369223e+09,330553.160278,330553.159869,2.369223e+09
4,5,5,7,13,CALHOUN,2000-05-16T00:00:00.000Z,1.604809e+10,6.313440e+05,7,Calhoun,...,6,0,0,0,0,0,1.487627e+09,192207.890331,192207.890041,1.487627e+09

In [8]:
covid.describe()

,OBJECTID_12_13,OBJECTID,DEPCODE,COUNTY,ShapeSTAre,ShapeSTLen,OBJECTID_1,OBJECTID_12,DEPCODE_1,COUNTYN,...,T_negative,T_pending,T_positive,FLandNonFLDeaths,EverMon,MonNow,Shape__Area,Shape__Length,Shape_Length,Shape_Area
count,68.00000,68.000000,68.000000,68.000000,6.700000e+01,6.700000e+01,68.00000,68.00000,68.000000,68.000000,...,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,6.800000e+01,6.800000e+01,6.800000e+01,6.800000e+01
mean,34.50000,48.191176,48.191176,80.705882,2.342932e+10,1.048655e+06,34.50000,34.50000,48.191176,80.705882,...,193.044118,14.823529,20.764706,0.264706,35.014706,18.367647,2.149516e+09,3.158988e+05,3.158988e+05,2.149516e+09
std,19.77372,118.610646,118.610646,119.456613,1.149607e+10,5.982756e+05,19.77372,19.77372,118.610646,119.456613,...,406.210167,27.426396,56.765850,0.745487,66.210315,43.389215,1.080909e+09,1.834328e+05,1.834328e+05,1.080909e+09
min,1.00000,1.000000,1.000000,1.000000,6.963394e+09,4.206436e+05,1.00000,1.00000,1.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.267574e+08,7.323129e+04,7.323129e+04,4.267574e+08
25%,17.75000,17.750000,17.750000,34.500000,1.620782e+10,7.373391e+05,17.75000,17.75000,17.750000,34.500000,...,13.500000,1.000000,0.000000,0.000000,1.000000,0.000000,1.501807e+09,2.236588e+05,2.236588e+05,1.501807e+09
50%,34.50000,34.500000,34.500000,68.000000,1.964766e+10,8.939740e+05,34.50000,34.50000,34.500000,68.000000,...,58.000000,4.500000,4.000000,0.000000,6.000000,2.000000,1.824662e+09,2.723376e+05,2.723376e+05,1.824662e+09
75%,51.25000,51.250000,51.250000,101.500000,2.820891e+10,1.172507e+06,51.25000,51.25000,51.250000,101.500000,...,172.250000,19.000000,14.250000,0.000000,38.000000,13.250000,2.608797e+09,3.567754e+05,3.567754e+05,2.608797e+09
max,68.00000,999.000000,999.000000,999.000000,6.149159e+10,4.591182e+06,68.00000,68.00000,999.000000,999.000000,...,2169.000000,182.000000,338.000000,3.000000,314.000000,248.000000,5.710099e+09,1.399293e+06,1.399293e+06,5.710099e+09